name: iOS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout your code
      - uses: actions/checkout@v2

      # Make sure the latest GraalVM is installed.
      # after this step env.JAVA_HOME and env.GRAALVM_HOME will point to the GraalVM location
      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        # set GITHUB_TOKEN to avoid exceeding GitHub's API rate limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Manually set Maven version
      - name: Install Maven 3.8.8
        run: |
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz | tar xz -C $HOME
          echo "M2_HOME=$HOME/apache-maven-3.8.8" >> $GITHUB_ENV
          echo "$HOME/apache-maven-3.8.8/bin" >> $GITHUB_PATH

      # Verify Maven Version
      - name: Verify Maven Version
        run: mvn -version

      # Build your project using Maven
      # The ios profile is used, which means a native build will be created for the gluonfx target ios.
      - name: Gluon Build
        run: mvn -Pios-sim gluonfx:build gluonfx:package
      
      # Upload Build Artefact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-build-artifact
          path: |
            /Users/runner/work/helloscala/helloscala/target
